version: "3.9"

services:
  api:
    build: .
    container_name: devsecops_api
    environment:
      - APP_NAME=DevSecOps Demo
      - API_KEY=super-secret-key
      - DB_PASSWORD=admin123  # Добавил: слабый пароль в переменных
    ports:
      - "8000:8000"
    depends_on:
      - redis
    privileged: true  # ЯВНАЯ УЯЗВИМОСТЬ: контейнер с полными привилегиями
    user: root  # ЯВНАЯ УЯЗВИМОСТЬ: запуск от root

  redis:
    image: redis:7-alpine
    container_name: devsecops_redis
    ports:
      - "0.0.0.0:6379:6379"  # ЯВНАЯ УЯЗВИМОСТЬ: публичный доступ к Redis
    # Нет пароля для Redis (Checkov будет ругаться)

  reverse-proxy:
    image: nginx:alpine
    container_name: devsecops_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/passwd:/etc/passwd:ro  # ЯВНАЯ УЯЗВИМОСТЬ: монтирование системного файла
    depends_on:
      - api
