name: Container security

on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t devsecops-demo .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-demo
