name: Docker Security

on:
  push:
    branches: [ "master" ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t devsecops-demo .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-demo
          severity: HIGH,CRITICAL
